env:
  global:
    - CC_TEST_REPORTER_ID=8fcebf7e2c6b4c8469ea9ad2e6e4db9c9565ed2e018fb136aa240dad366884e5
language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://bradwindy.github.io/angular-course-proj/
after_script:
  - ls -a
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/angular-course-proj/lcov.info
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
deploy:
  provider: pages
  local_dir: dist/angular-course-proj
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
